#pragma once

#include <Eigen/Dense>
#include <random>
#include <vector>

namespace aggregate {

class Box;
class Ellipsoid;
class Fibre;
class Disk;

/**
 * Sequential trial-and-error placer for ellipsoidal and fibrous inclusions.
 *
 * Re-implementation of `placement_aggregates_periodic.m` and
 * `fiber_generation_and_placement_periodic.m`:
 *
 *   - Random centre uniformly in [0, lx]×[0, ly]×[0, lz]
 *   - Random ellipsoid orientation via Shoemake's quaternion sampler
 *     (uniform on SO(3)); fibre direction via Marsaglia (uniform on S²)
 *   - Boundary detection per axis: if the candidate intersects either side
 *     of a non-periodic boundary, reject; otherwise mark and (when needed)
 *     shift the centre by −lx_i so the primary representation extends
 *     naturally past the far face
 *   - Periodic ghosts: 2^k − 1 copies for k crossed axes, at the canonical
 *     +lx_i shifts; ghosts are stored on `Box` for collision tests but
 *     never written to the packing file
 *   - Pairwise overlap: cheap inscribed/bounding sphere bounds first, then
 *     the Alfano-Greer eigenvalue test (`ellipsoidsIntersect`) only when
 *     the bounds are inconclusive. Fibre-fibre crossings are permitted
 *     (matching the Matlab convention) — only fibre-vs-ellipsoid is checked.
 *
 * The placer leaves all inclusions previously stored on `Box` untouched —
 * existing aggregates and fibres are treated as fixed obstacles. New
 * placements respect `box.giveMaximumIterations()` per attempt.
 */
class Placer
{
public:
    /// Bind the placer to a `box` (which receives accepted inclusions and
    /// supplies dimensions, periodicity, and the iteration cap) and an `rng`
    /// (used for centre, orientation, and direction sampling).
    Placer(Box &box, std::mt19937 &rng);

    /// Try to place a single ellipsoid of the given semi-axes.
    /// On success the primary and any periodic ghosts are appended to `box`.
    bool placeOne(const Eigen::Vector3d &semiAxes);

    /// Place the supplied list of sizes in order. Returns the number that
    /// failed to place within `box.giveMaximumIterations()` attempts each.
    int placeBatch(const std::vector<Eigen::Vector3d> &sizes);

    /// Try to place a single fibre of the given length and diameter. The
    /// orientation is sampled uniformly on S² (Marsaglia). Overlap is
    /// checked against ellipsoids only — fibre-fibre crossings are
    /// permitted, matching the Matlab convention.
    bool placeFibre(double length, double diameter);

    /// Place `count` fibres in sequence. Returns the number that failed to
    /// place within `box.giveMaximumIterations()` attempts each.
    int placeFibreBatch(int count, double length, double diameter);

    /// 2D path: try to place a single disk of the given radius. Centre is
    /// drawn uniformly in `[0, lx] × [0, ly]`; periodic ghosts are emitted
    /// when the disk crosses a periodic boundary; non-periodic crossings
    /// reject. Overlap test is the analytic distance check between disk
    /// centres.
    bool placeOneDisk(double radius);

    /// 2D path: place the supplied list of radii in order. Returns the
    /// number that failed to place within `box.giveMaximumIterations()`
    /// attempts each.
    int placeDiskBatch(const std::vector<double> &radii);

private:
    bool detectBoundaries(Eigen::Vector3d &centre,
                          const Eigen::Vector3d &angles,
                          const Eigen::Vector3d &semiAxes,
                          int &bitmask) const;

    bool detectFibreBoundaries(Eigen::Vector3d &centre,
                               Eigen::Vector3d &endpointA,
                               Eigen::Vector3d &endpointB,
                               int &bitmask) const;

    bool overlapsAnyExisting(const Ellipsoid &candidate,
                             const std::vector<Eigen::Vector3d> &shifts) const;

    bool fibreOverlapsAnyEllipsoid(const Fibre &candidate,
                                   const std::vector<Eigen::Vector3d> &shifts) const;

    Box &box;
    std::mt19937 &rng;
};

/// Periodic shift vectors generated by a `bitmask` over crossed axes (bit
/// i set ⇔ the candidate crosses axis i). Excludes the (0,0,0) shift.
std::vector<Eigen::Vector3d> ghostShifts(const Eigen::Vector3d &boxDims, int bitmask);

} // namespace aggregate
