#pragma once

#include <Eigen/Dense>
#include <random>
#include <vector>

namespace aggregate {

class Box;
class Ellipsoid;
class Fibre;

/**
 * Sequential trial-and-error placer for ellipsoidal inclusions.
 *
 * Faithful re-implementation of `placement_aggregates_periodic.m`:
 *
 *   - Random centre uniformly in [0, lx]×[0, ly]×[0, lz]
 *   - Random Euler angles via Matlab's mixed convention: phix, phiz uniform
 *     in [0, 2π); phiy = acos(2u−1) − π/2, giving uniform y-axis cosine
 *   - Boundary detection per axis: if the candidate intersects either side
 *     of a non-periodic boundary, reject; otherwise mark and (when needed)
 *     shift the centre by −lx_i so the primary representation extends
 *     naturally past the far face
 *   - Periodic ghosts: 2^k − 1 copies for k crossed axes, at the canonical
 *     +lx_i shifts; ghosts are stored on `Box` for collision tests but
 *     never written to the packing file
 *   - Pairwise overlap: cheap inscribed/bounding sphere bounds first, then
 *     the Alfano-Greer eigenvalue test (`ellipsoidsIntersect`) only when
 *     the bounds are inconclusive
 *
 * The placer leaves all inclusions previously stored on `Box` untouched —
 * existing aggregates and fibres are treated as fixed obstacles. New
 * placements respect `box.giveMaximumIterations()` per attempt.
 */
class Placer
{
public:
    Placer(Box &box, std::mt19937 &rng);

    /// Try to place a single ellipsoid of the given semi-axes.
    /// On success the primary and any periodic ghosts are appended to `box`.
    bool placeOne(const Eigen::Vector3d &semiAxes);

    /// Place the supplied list of sizes in order. Returns the number that
    /// failed to place within `box.giveMaximumIterations()` attempts each.
    int placeBatch(const std::vector<Eigen::Vector3d> &sizes);

    /// Try to place a single fibre of the given length and diameter. The
    /// orientation is sampled uniformly on S² (Marsaglia). Overlap is
    /// checked against ellipsoids only — fibre-fibre crossings are
    /// permitted, matching the Matlab convention.
    bool placeFibre(double length, double diameter);

    /// Place `count` fibres in sequence. Returns the number that failed to
    /// place within `box.giveMaximumIterations()` attempts each.
    int placeFibreBatch(int count, double length, double diameter);

private:
    bool detectBoundaries(Eigen::Vector3d &centre,
                          const Eigen::Vector3d &angles,
                          const Eigen::Vector3d &semiAxes,
                          int &bitmask) const;

    bool detectFibreBoundaries(Eigen::Vector3d &centre,
                               Eigen::Vector3d &endpointA,
                               Eigen::Vector3d &endpointB,
                               int &bitmask) const;

    bool overlapsAnyExisting(const Ellipsoid &candidate,
                             const std::vector<Eigen::Vector3d> &shifts) const;

    bool fibreOverlapsAnyEllipsoid(const Fibre &candidate,
                                   const std::vector<Eigen::Vector3d> &shifts) const;

    Box &box;
    std::mt19937 &rng;
};

/// Periodic shift vectors generated by a `bitmask` over crossed axes (bit
/// i set ⇔ the candidate crosses axis i). Excludes the (0,0,0) shift.
std::vector<Eigen::Vector3d> ghostShifts(const Eigen::Vector3d &boxDims, int bitmask);

} // namespace aggregate
